import 'package:forui/forui.dart';
import 'package:material_ui/material_ui.dart';

import 'palette/tailwind_colors.dart';

part 'colors.dart';
part 'typography.dart';
part 'style.dart';
part 'icons.dart';

/// Generated by Forui CLI.
///
/// Regenerate using "dart forui theme create --preset aabbbb".
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart run forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
// FThemeData get lightTheme {
//   // Change this to false to use the desktop variant of this theme.
//   const touch = true;

//   final colors = lightColors;

//   final typography = _typography(colors: colors, touch: touch);

//   final icons = _icons();

//   final style = _style(colors: colors, typography: typography, touch: touch);

//   return FThemeData(
//     colors: colors,
//     typography: typography,
//     icons: icons,
//     style: style,
//     touch: touch,
//   );
// }

// FThemeData get darkTheme {
//   // Change this to false to use the desktop variant of this theme.
//   const touch = true;

//   final colors = darkColors;

//   final typography = _typography(colors: colors, touch: touch);

//   final icons = _icons();

//   final style = _style(colors: colors, typography: typography, touch: touch);

//   return FThemeData(
//     colors: colors,
//     typography: typography,
//     icons: icons,
//     style: style,
//     touch: touch,
//   );
// }

abstract final class ArcheTheme {
  static final light = FPlatformThemeData(
    desktop: () => _buildTheme(colors: lightColors, touch: false),
    touch: () => _buildTheme(colors: lightColors, touch: true),
  );

  static final dark = FPlatformThemeData(
    desktop: () => _buildTheme(colors: darkColors, touch: false),
    touch: () => _buildTheme(colors: darkColors, touch: true),
  );

  static FThemeData _buildTheme({required FColors colors, required bool touch}) {
    final typography = _typography(colors: colors, touch: touch);
    final icons = _icons();
    final style = _style(colors: colors, typography: typography, touch: touch);

    return FThemeData(
      colors: colors,
      typography: typography,
      icons: icons,
      style: style,
      touch: touch,
    );
  }
}
